export const AGENT = 'AGENT'
export const REPOBOT = 'REPOBOT'
export const TIME = 'TIME'
export const SPACE = 'SPACE'
export const EARTH = 'EARTH'
export const agent = 'agent'
export const repobot = 'repobot'

export const SHADE = 'SHADE'
export const SOLID = 'SOLID'
export const MARKET = 'MARKET'
export const LIBRARY = 'LIBRARY'
